version: "0027--11-Sep-2022"
copyright: "2022"
author: "sherlockjack"
title: "Operating Systems 2022-2"
githublink: "https://github.com/sherlockjack/os222/"
myloglink: "/TXT/mylog.txt"
encoding: UTF-8
markdown: kramdown
input: GFM
hard_wrap: false
github: [metadata]
